-- MySQL Script generated by MySQL Workbench
-- Sat Nov 12 18:50:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema GPE_DEV
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GPE_DEV` ;

-- -----------------------------------------------------
-- Schema GPE_DEV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GPE_DEV` DEFAULT CHARACTER SET utf8 ;
USE `GPE_DEV` ;

-- -----------------------------------------------------
-- Table `GPE_DEV`.`USER_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GPE_DEV`.`USER_INFO` ;

CREATE TABLE IF NOT EXISTS `GPE_DEV`.`USER_INFO` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(255) NULL,
  `LAST_NAME` VARCHAR(255) NULL,
  `TITLE` VARCHAR(255) NULL,
  `EMAIL_ID` VARCHAR(255) NULL,
  `PASSWORD` VARCHAR(255) NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GPE_DEV`.`VENDOR_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GPE_DEV`.`VENDOR_INFO` ;

CREATE TABLE IF NOT EXISTS `GPE_DEV`.`VENDOR_INFO` (
  `VENDOR_ID` INT NOT NULL AUTO_INCREMENT,
  `VENDOR_NUMBER` VARCHAR(255) NULL,
  `VENDOR_NAME` VARCHAR(255) NULL,
  `VENDOR_ESTABLISHMENT_YEAR` VARCHAR(255) NULL,
  PRIMARY KEY (`VENDOR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GPE_DEV`.`PRODUCTS_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GPE_DEV`.`PRODUCTS_INFO` ;

CREATE TABLE IF NOT EXISTS `GPE_DEV`.`PRODUCTS_INFO` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_IDENTIFIER` VARCHAR(255) NULL,
  `VENDOR_ID` INT NULL,
  `PRODUCT_NAME` VARCHAR(255) NULL,
  `PRODUCT_DESCRIPTION` VARCHAR(255) NULL,
  `BRAND` VARCHAR(255) NULL,
  `CATEGORY` VARCHAR(255) NULL,
  `SUB_CATEGORY` VARCHAR(255) NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  CONSTRAINT `VENDOR_ID_PRODUCTS_INFO`
    FOREIGN KEY (`VENDOR_ID`)
    REFERENCES `GPE_DEV`.`VENDOR_INFO` (`VENDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GPE_DEV`.`PRICES_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GPE_DEV`.`PRICES_INFO` ;

CREATE TABLE IF NOT EXISTS `GPE_DEV`.`PRICES_INFO` (
  `PRODUCT_ID` INT NOT NULL,
  `VENDOR_ID` INT NOT NULL,
  `PRODUCT_NAME` VARCHAR(255) NOT NULL,
  `AMAZON_PRICE` DECIMAL(45,4) NULL,
  `FLIPKART_PRICE` DECIMAL(45,4) NULL,
  `ALIBABA_PRICE` DECIMAL(45,4) NULL,
  `SNAPDEAL_PRICE` DECIMAL(45,4) NULL,
  CONSTRAINT `PRODUCT_ID_PRICES_INFO`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `GPE_DEV`.`PRODUCTS_INFO` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VENDOR_ID_PRICES_INFO`
    FOREIGN KEY (`VENDOR_ID`)
    REFERENCES `GPE_DEV`.`VENDOR_INFO` (`VENDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;